name: thisisMagnify
favicon: null
layout_spectrum: 0.7008725348860025
typography_spectrum: 0.8298607708420604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3746716065797955
  lightness: 0.4257617429830134
  saturation: 0.38878878206014633
  rhythmicContrast: 0.79685786832124
purpose: []
